[project]
name = "mental-maths"
version = "0.3.0"
description = "a simple mental maths terminal UI"
requires-python = ">=3.13"
dependencies = []

[project.scripts]
mental-maths = "mentalmaths.__main__:run"

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.hatch.build.targets.wheel]
packages = ["mentalmaths"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff.lint]
select = ["E", "F", "W", "I", "B", "UP", "SIM"]
ignore = ["E501"]
